import type { Team, Player } from './types'

export const DEFAULT_TEAMS: Team[] = [
  { id: 1,  name: '鹿島アントラーズ',         league: 'J1', colors: ['#C8102E', '#000000', '#FFFFFF'] },
  { id: 2,  name: '柏レイソル',               league: 'J1', colors: ['#FFD700', '#000000', '#FFD700'] },
  { id: 3,  name: 'FC東京',                  league: 'J1', colors: ['#003087', '#E8112D', '#FFFFFF'] },
  { id: 4,  name: '川崎フロンターレ',           league: 'J1', colors: ['#009BDB', '#000000', '#009BDB'] },
  { id: 5,  name: '横浜F・マリノス',           league: 'J1', colors: ['#003087', '#E8112D', '#FFFFFF'] },
  { id: 6,  name: '湘南ベルマーレ',            league: 'J1', colors: ['#009944', '#FF0000', '#FFFFFF'] },
  { id: 7,  name: '清水エスパルス',            league: 'J1', colors: ['#FF6600', '#0033A0', '#FFFFFF'] },
  { id: 8,  name: '名古屋グランパス',           league: 'J1', colors: ['#CC0000', '#FFFFFF', '#CC0000'] },
  { id: 9,  name: 'ガンバ大阪',               league: 'J1', colors: ['#003087', '#000000', '#003087'] },
  { id: 10, name: 'セレッソ大阪',              league: 'J1', colors: ['#FF69B4', '#003087', '#FFFFFF'] },
  { id: 11, name: 'ヴィッセル神戸',            league: 'J1', colors: ['#E8112D', '#000000', '#FFFFFF'] },
  { id: 12, name: 'サンフレッチェ広島',         league: 'J1', colors: ['#6A0DAD', '#FFFFFF', '#6A0DAD'] },
  { id: 13, name: 'アビスパ福岡',              league: 'J1', colors: ['#003087', '#E8112D', '#FFFFFF'] },
  { id: 14, name: '浦和レッズ',               league: 'J1', colors: ['#E8112D', '#E8112D', '#FFFFFF'] },
  { id: 15, name: '北海道コンサドーレ札幌',      league: 'J1', colors: ['#E8112D', '#000000', '#FFFFFF'] },
  { id: 16, name: 'アルビレックス新潟',         league: 'J1', colors: ['#F5A623', '#000000', '#FFFFFF'] },
  { id: 17, name: '東京ヴェルディ',            league: 'J1', colors: ['#009944', '#009944', '#FFFFFF'] },
  { id: 18, name: '京都サンガF.C.',           league: 'J1', colors: ['#6A0DAD', '#FFFFFF', '#6A0DAD'] },
]

export const DEFAULT_PLAYERS: Player[] = [
  // 1: 鹿島アントラーズ
  { id: 101, teamId: 1, num: 1,  name: '早川 友基',   furi: 'はやかわ ともき',   pos: 'GK' },
  { id: 102, teamId: 1, num: 3,  name: '関川 郁万',   furi: 'せきかわ いくま',   pos: 'DF' },
  { id: 103, teamId: 1, num: 4,  name: '植田 直通',   furi: 'うえだ なおみち',   pos: 'DF' },
  { id: 104, teamId: 1, num: 16, name: '佐野 海舟',   furi: 'さの かいしゅう',   pos: 'DF' },
  { id: 105, teamId: 1, num: 8,  name: '田中 駿汰',   furi: 'たなか しゅんた',   pos: 'MF' },
  { id: 106, teamId: 1, num: 10, name: '荒木 遼太郎', furi: 'あらき りょうたろう', pos: 'MF' },
  { id: 107, teamId: 1, num: 15, name: '仲間 隼斗',   furi: 'なかま はやと',     pos: 'MF' },
  { id: 108, teamId: 1, num: 25, name: '知念 慶',     furi: 'ちねん けい',       pos: 'MF' },
  { id: 109, teamId: 1, num: 9,  name: '鈴木 優磨',   furi: 'すずき ゆうま',     pos: 'FW' },
  { id: 110, teamId: 1, num: 11, name: 'エレケ',      furi: 'えれけ',           pos: 'FW' },

  // 2: 柏レイソル
  { id: 201, teamId: 2, num: 1,  name: '松本 健太',   furi: 'まつもと けんた',   pos: 'GK' },
  { id: 202, teamId: 2, num: 3,  name: '古賀 太陽',   furi: 'こが たいよう',     pos: 'DF' },
  { id: 203, teamId: 2, num: 5,  name: '犬飼 智也',   furi: 'いぬかい ともや',   pos: 'DF' },
  { id: 204, teamId: 2, num: 22, name: '升掛 友護',   furi: 'ますかけ ゆうご',   pos: 'DF' },
  { id: 205, teamId: 2, num: 7,  name: '椎橋 慧也',   furi: 'しいはし けいや',   pos: 'MF' },
  { id: 206, teamId: 2, num: 8,  name: '高嶺 朋樹',   furi: 'たかみね ともき',   pos: 'MF' },
  { id: 207, teamId: 2, num: 10, name: 'マテウス サヴィオ', furi: 'まてうす さびお', pos: 'MF' },
  { id: 208, teamId: 2, num: 18, name: '戸嶋 祥郎',   furi: 'とじま よしろう',   pos: 'MF' },
  { id: 209, teamId: 2, num: 9,  name: '細谷 真大',   furi: 'ほそや まひろ',     pos: 'FW' },
  { id: 210, teamId: 2, num: 11, name: 'フロート',    furi: 'ふろーと',         pos: 'FW' },

  // 3: FC東京
  { id: 301, teamId: 3, num: 1,  name: '野澤 大志ブランドン', furi: 'のざわ だいしぶらんどん', pos: 'GK' },
  { id: 302, teamId: 3, num: 5,  name: '木本 恭生',   furi: 'きもと やすお',     pos: 'DF' },
  { id: 303, teamId: 3, num: 6,  name: '森重 真人',   furi: 'もりしげ まさと',   pos: 'DF' },
  { id: 304, teamId: 3, num: 33, name: '白井 永地',   furi: 'しらい えいち',     pos: 'DF' },
  { id: 305, teamId: 3, num: 7,  name: '松木 玖生',   furi: 'まつき くう',       pos: 'MF' },
  { id: 306, teamId: 3, num: 8,  name: '高 宇洋',     furi: 'こう うひろ',       pos: 'MF' },
  { id: 307, teamId: 3, num: 10, name: '荒川 颯',     furi: 'あらかわ そう',     pos: 'MF' },
  { id: 308, teamId: 3, num: 16, name: '安斎 颯馬',   furi: 'あんざい そうま',   pos: 'MF' },
  { id: 309, teamId: 3, num: 9,  name: 'ディエゴ オリヴェイラ', furi: 'でぃえご おりびえいら', pos: 'FW' },
  { id: 310, teamId: 3, num: 11, name: '遠藤 渓太',   furi: 'えんどう けいた',   pos: 'FW' },

  // 4: 川崎フロンターレ
  { id: 401, teamId: 4, num: 1,  name: '上福元 直人', furi: 'かみふくもと なおと', pos: 'GK' },
  { id: 402, teamId: 4, num: 3,  name: '佐々木 旭',   furi: 'ささき あさひ',     pos: 'DF' },
  { id: 403, teamId: 4, num: 4,  name: '山村 和也',   furi: 'やまむら かずや',   pos: 'DF' },
  { id: 404, teamId: 4, num: 5,  name: '三浦 颯太',   furi: 'みうら そうた',     pos: 'DF' },
  { id: 405, teamId: 4, num: 6,  name: '大島 僚太',   furi: 'おおしま りょうた', pos: 'MF' },
  { id: 406, teamId: 4, num: 8,  name: '橘田 健人',   furi: 'きった けんと',     pos: 'MF' },
  { id: 407, teamId: 4, num: 10, name: '脇坂 泰斗',   furi: 'わきさか やすと',   pos: 'MF' },
  { id: 408, teamId: 4, num: 14, name: '家長 昭博',   furi: 'いえなが あきひろ', pos: 'MF' },
  { id: 409, teamId: 4, num: 9,  name: '山田 新',     furi: 'やまだ あらた',     pos: 'FW' },
  { id: 410, teamId: 4, num: 11, name: 'マルシーニョ', furi: 'まるしーにょ',     pos: 'FW' },

  // 5: 横浜F・マリノス
  { id: 501, teamId: 5, num: 1,  name: '一森 純',     furi: 'いちもり じゅん',   pos: 'GK' },
  { id: 502, teamId: 5, num: 3,  name: '永戸 勝也',   furi: 'ながと かつや',     pos: 'DF' },
  { id: 503, teamId: 5, num: 4,  name: '畠中 槙之輔', furi: 'はたけなか まきのすけ', pos: 'DF' },
  { id: 504, teamId: 5, num: 13, name: '松原 健',     furi: 'まつばら けん',     pos: 'DF' },
  { id: 505, teamId: 5, num: 5,  name: '渡辺 皓太',   furi: 'わたなべ こうた',   pos: 'MF' },
  { id: 506, teamId: 5, num: 8,  name: '喜田 拓也',   furi: 'きた たくや',       pos: 'MF' },
  { id: 507, teamId: 5, num: 10, name: '西村 拓真',   furi: 'にしむら たくま',   pos: 'MF' },
  { id: 508, teamId: 5, num: 18, name: '水沼 宏太',   furi: 'みずぬま こうた',   pos: 'MF' },
  { id: 509, teamId: 5, num: 9,  name: 'アンデルソン ロペス', furi: 'あんでるそん ろぺす', pos: 'FW' },
  { id: 510, teamId: 5, num: 11, name: 'エウベル',    furi: 'えうべる',         pos: 'FW' },

  // 6: 湘南ベルマーレ
  { id: 601, teamId: 6, num: 1,  name: '富居 大樹',   furi: 'とみい だいき',     pos: 'GK' },
  { id: 602, teamId: 6, num: 3,  name: '山本 脩斗',   furi: 'やまもと しゅうと', pos: 'DF' },
  { id: 603, teamId: 6, num: 4,  name: '大岩 一貴',   furi: 'おおいわ かずき',   pos: 'DF' },
  { id: 604, teamId: 6, num: 5,  name: '杉岡 大暉',   furi: 'すぎおか だいき',   pos: 'DF' },
  { id: 605, teamId: 6, num: 6,  name: '茨田 陽生',   furi: 'いばらた はるき',   pos: 'MF' },
  { id: 606, teamId: 6, num: 8,  name: '田中 聡',     furi: 'たなか さとし',     pos: 'MF' },
  { id: 607, teamId: 6, num: 10, name: '池田 昌生',   furi: 'いけだ まさき',     pos: 'MF' },
  { id: 608, teamId: 6, num: 14, name: '奥野 耕平',   furi: 'おくの こうへい',   pos: 'MF' },
  { id: 609, teamId: 6, num: 9,  name: '大橋 祐紀',   furi: 'おおはし ゆうき',   pos: 'FW' },
  { id: 610, teamId: 6, num: 11, name: 'タリク',      furi: 'たりく',           pos: 'FW' },

  // 7: 清水エスパルス
  { id: 701, teamId: 7, num: 1,  name: '権田 修一',   furi: 'ごんだ しゅういち', pos: 'GK' },
  { id: 702, teamId: 7, num: 3,  name: '原 輝綺',     furi: 'はら てるき',       pos: 'DF' },
  { id: 703, teamId: 7, num: 4,  name: '蓮川 雄大',   furi: 'はすかわ ゆうだい', pos: 'DF' },
  { id: 704, teamId: 7, num: 5,  name: '北爪 健吾',   furi: 'きたづめ けんご',   pos: 'DF' },
  { id: 705, teamId: 7, num: 6,  name: '宮本 航汰',   furi: 'みやもと こうた',   pos: 'MF' },
  { id: 706, teamId: 7, num: 8,  name: '中村 慶太',   furi: 'なかむら けいた',   pos: 'MF' },
  { id: 707, teamId: 7, num: 10, name: '乾 貴士',     furi: 'いぬい たかし',     pos: 'MF' },
  { id: 708, teamId: 7, num: 20, name: '矢島 慎也',   furi: 'やじま しんや',     pos: 'MF' },
  { id: 709, teamId: 7, num: 9,  name: 'チアゴ サンタナ', furi: 'ちあご さんたな', pos: 'FW' },
  { id: 710, teamId: 7, num: 11, name: '北川 航也',   furi: 'きたがわ こうや',   pos: 'FW' },

  // 8: 名古屋グランパス
  { id: 801, teamId: 8, num: 1,  name: 'ランゲラック', furi: 'らんげらっく',     pos: 'GK' },
  { id: 802, teamId: 8, num: 3,  name: '中谷 進之介', furi: 'なかたに しんのすけ', pos: 'DF' },
  { id: 803, teamId: 8, num: 4,  name: '丸山 祐市',   furi: 'まるやま ゆういち', pos: 'DF' },
  { id: 804, teamId: 8, num: 19, name: '河面 旺成',   furi: 'こうも おうせい',   pos: 'DF' },
  { id: 805, teamId: 8, num: 6,  name: '稲垣 祥',     furi: 'いながき しょう',   pos: 'MF' },
  { id: 806, teamId: 8, num: 8,  name: '米本 拓司',   furi: 'よねもと たくじ',   pos: 'MF' },
  { id: 807, teamId: 8, num: 10, name: '森島 司',     furi: 'もりしま つかさ',   pos: 'MF' },
  { id: 808, teamId: 8, num: 14, name: '和泉 竜司',   furi: 'いずみ りゅうじ',   pos: 'MF' },
  { id: 809, teamId: 8, num: 9,  name: 'パトリック',  furi: 'ぱとりっく',       pos: 'FW' },
  { id: 810, teamId: 8, num: 11, name: '永井 謙佑',   furi: 'ながい けんすけ',   pos: 'FW' },

  // 9: ガンバ大阪
  { id: 901, teamId: 9, num: 1,  name: '東口 順昭',   furi: 'ひがしぐち のりあき', pos: 'GK' },
  { id: 902, teamId: 9, num: 3,  name: '三浦 弦太',   furi: 'みうら げんた',     pos: 'DF' },
  { id: 903, teamId: 9, num: 5,  name: '昌子 源',     furi: 'しょうじ げん',     pos: 'DF' },
  { id: 904, teamId: 9, num: 22, name: '佐藤 瑶大',   furi: 'さとう ようだい',   pos: 'DF' },
  { id: 905, teamId: 9, num: 6,  name: '山本 悠樹',   furi: 'やまもと ゆうき',   pos: 'MF' },
  { id: 906, teamId: 9, num: 8,  name: '福田 湧矢',   furi: 'ふくだ ゆうや',     pos: 'MF' },
  { id: 907, teamId: 9, num: 10, name: '宇佐美 貴史', furi: 'うさみ たかふみ',   pos: 'MF' },
  { id: 908, teamId: 9, num: 17, name: '坂本 一彩',   furi: 'さかもと いっさ',   pos: 'MF' },
  { id: 909, teamId: 9, num: 9,  name: 'イッサム ジェバリ', furi: 'いっさむ じぇばり', pos: 'FW' },
  { id: 910, teamId: 9, num: 11, name: '食野 亮太郎', furi: 'けの りょうたろう', pos: 'FW' },

  // 10: セレッソ大阪
  { id: 1001, teamId: 10, num: 1,  name: 'キム ジンヒョン', furi: 'きむ じんひょん', pos: 'GK' },
  { id: 1002, teamId: 10, num: 3,  name: '毎熊 晟矢',  furi: 'まいくま せいや',   pos: 'DF' },
  { id: 1003, teamId: 10, num: 4,  name: '鳥海 晃司',  furi: 'とりうみ こうじ',   pos: 'DF' },
  { id: 1004, teamId: 10, num: 5,  name: '西尾 隆矢',  furi: 'にしお たかや',     pos: 'DF' },
  { id: 1005, teamId: 10, num: 6,  name: '奥埜 博亮',  furi: 'おくの ひろあき',   pos: 'MF' },
  { id: 1006, teamId: 10, num: 8,  name: '香川 真司',  furi: 'かがわ しんじ',     pos: 'MF' },
  { id: 1007, teamId: 10, num: 10, name: '清武 弘嗣',  furi: 'きよたけ ひろし',   pos: 'MF' },
  { id: 1008, teamId: 10, num: 17, name: '田中 駿汰',  furi: 'たなか しゅんた',   pos: 'MF' },
  { id: 1009, teamId: 10, num: 9,  name: 'レオ セアラ', furi: 'れお せあら',      pos: 'FW' },
  { id: 1010, teamId: 10, num: 11, name: '加藤 陸次樹', furi: 'かとう りくつぎ',  pos: 'FW' },

  // 11: ヴィッセル神戸
  { id: 1101, teamId: 11, num: 1,  name: '前川 黛也',  furi: 'まえかわ たいや',   pos: 'GK' },
  { id: 1102, teamId: 11, num: 3,  name: '酒井 高徳',  furi: 'さかい ごうとく',   pos: 'DF' },
  { id: 1103, teamId: 11, num: 4,  name: '山川 哲史',  furi: 'やまかわ さとし',   pos: 'DF' },
  { id: 1104, teamId: 11, num: 5,  name: '本多 勇喜',  furi: 'ほんだ ゆうき',     pos: 'DF' },
  { id: 1105, teamId: 11, num: 6,  name: '扇原 貴宏',  furi: 'おうぎはら たかひろ', pos: 'MF' },
  { id: 1106, teamId: 11, num: 8,  name: '佐々木 大樹', furi: 'ささき だいき',    pos: 'MF' },
  { id: 1107, teamId: 11, num: 10, name: '井手口 陽介', furi: 'いでぐち ようすけ', pos: 'MF' },
  { id: 1108, teamId: 11, num: 16, name: '汰木 康也',  furi: 'ゆるぎ こうや',     pos: 'MF' },
  { id: 1109, teamId: 11, num: 9,  name: '大迫 勇也',  furi: 'おおさこ ゆうや',   pos: 'FW' },
  { id: 1110, teamId: 11, num: 11, name: '武藤 嘉紀',  furi: 'むとう よしのり',   pos: 'FW' },

  // 12: サンフレッチェ広島
  { id: 1201, teamId: 12, num: 1,  name: '大迫 敬介',  furi: 'おおさこ けいすけ', pos: 'GK' },
  { id: 1202, teamId: 12, num: 3,  name: '塩谷 司',    furi: 'しおたに つかさ',   pos: 'DF' },
  { id: 1203, teamId: 12, num: 4,  name: '佐々木 翔',  furi: 'ささき しょう',     pos: 'DF' },
  { id: 1204, teamId: 12, num: 5,  name: '荒木 隼人',  furi: 'あらき はやと',     pos: 'DF' },
  { id: 1205, teamId: 12, num: 6,  name: '川辺 駿',    furi: 'かわべ しゅん',     pos: 'MF' },
  { id: 1206, teamId: 12, num: 8,  name: '青山 敏弘',  furi: 'あおやま としひろ', pos: 'MF' },
  { id: 1207, teamId: 12, num: 10, name: '森島 司',    furi: 'もりしま つかさ',   pos: 'MF' },
  { id: 1208, teamId: 12, num: 18, name: '満田 誠',    furi: 'みつだ まこと',     pos: 'MF' },
  { id: 1209, teamId: 12, num: 9,  name: 'ゴンサロ パシェンシア', furi: 'ごんさろ ぱしぇんしあ', pos: 'FW' },
  { id: 1210, teamId: 12, num: 11, name: '棚田 遼',    furi: 'たなだ りょう',     pos: 'FW' },

  // 13: アビスパ福岡
  { id: 1301, teamId: 13, num: 1,  name: '村上 昌謙',  furi: 'むらかみ まさのり', pos: 'GK' },
  { id: 1302, teamId: 13, num: 3,  name: '湯澤 聖人',  furi: 'ゆざわ きよと',     pos: 'DF' },
  { id: 1303, teamId: 13, num: 4,  name: '奈良 竜樹',  furi: 'なら たつき',       pos: 'DF' },
  { id: 1304, teamId: 13, num: 5,  name: '宮 大樹',    furi: 'みや だいき',       pos: 'DF' },
  { id: 1305, teamId: 13, num: 6,  name: '前 寛之',    furi: 'まえ ひろゆき',     pos: 'MF' },
  { id: 1306, teamId: 13, num: 8,  name: '重廣 卓也',  furi: 'しげひろ たくや',   pos: 'MF' },
  { id: 1307, teamId: 13, num: 10, name: '金森 健志',  furi: 'かなもり けんじ',   pos: 'MF' },
  { id: 1308, teamId: 13, num: 17, name: '紺野 和也',  furi: 'こんの かずや',     pos: 'MF' },
  { id: 1309, teamId: 13, num: 9,  name: 'ウェリントン', furi: 'うぇりんとん',    pos: 'FW' },
  { id: 1310, teamId: 13, num: 11, name: '岩崎 悠人',  furi: 'いわさき ゆうと',   pos: 'FW' },

  // 14: 浦和レッズ
  { id: 1401, teamId: 14, num: 1,  name: '西川 周作',  furi: 'にしかわ しゅうさく', pos: 'GK' },
  { id: 1402, teamId: 14, num: 3,  name: '酒井 宏樹',  furi: 'さかい ひろき',     pos: 'DF' },
  { id: 1403, teamId: 14, num: 4,  name: 'マリウス ホイブラーテン', furi: 'まりうす ほいぶらーてん', pos: 'DF' },
  { id: 1404, teamId: 14, num: 5,  name: '岩波 拓也',  furi: 'いわなみ たくや',   pos: 'DF' },
  { id: 1405, teamId: 14, num: 6,  name: '柴戸 海',    furi: 'しばと かい',       pos: 'MF' },
  { id: 1406, teamId: 14, num: 8,  name: '小泉 佳穂',  furi: 'こいずみ よしほ',   pos: 'MF' },
  { id: 1407, teamId: 14, num: 10, name: '大久保 智明', furi: 'おおくぼ とものり', pos: 'MF' },
  { id: 1408, teamId: 14, num: 14, name: '安居 海渡',  furi: 'やすい かいと',     pos: 'MF' },
  { id: 1409, teamId: 14, num: 9,  name: '興梠 慎三',  furi: 'こうろき しんぞう', pos: 'FW' },
  { id: 1410, teamId: 14, num: 11, name: 'ブライアン リンセン', furi: 'ぶらいあん りんせん', pos: 'FW' },

  // 15: 北海道コンサドーレ札幌
  { id: 1501, teamId: 15, num: 1,  name: '菅野 孝憲',  furi: 'すがの たかのり',   pos: 'GK' },
  { id: 1502, teamId: 15, num: 3,  name: '田中 駿汰',  furi: 'たなか しゅんた',   pos: 'DF' },
  { id: 1503, teamId: 15, num: 4,  name: '岡村 大八',  furi: 'おかむら だいや',   pos: 'DF' },
  { id: 1504, teamId: 15, num: 5,  name: '宮澤 裕樹',  furi: 'みやざわ ゆうき',   pos: 'DF' },
  { id: 1505, teamId: 15, num: 6,  name: '荒野 拓馬',  furi: 'あらの たくま',     pos: 'MF' },
  { id: 1506, teamId: 15, num: 8,  name: '深井 一希',  furi: 'ふかい かずき',     pos: 'MF' },
  { id: 1507, teamId: 15, num: 10, name: '小柏 剛',    furi: 'おがしわ つよし',   pos: 'MF' },
  { id: 1508, teamId: 15, num: 14, name: '駒井 善成',  furi: 'こまい よしなり',   pos: 'MF' },
  { id: 1509, teamId: 15, num: 9,  name: 'ガブリエル', furi: 'がぶりえる',       pos: 'FW' },
  { id: 1510, teamId: 15, num: 11, name: 'スパチョーク', furi: 'すぱちょーく',    pos: 'FW' },

  // 16: アルビレックス新潟
  { id: 1601, teamId: 16, num: 1,  name: '小島 亨介',  furi: 'おじま りょうすけ', pos: 'GK' },
  { id: 1602, teamId: 16, num: 3,  name: '藤原 奏哉',  furi: 'ふじわら そうや',   pos: 'DF' },
  { id: 1603, teamId: 16, num: 4,  name: '千葉 和彦',  furi: 'ちば かずひこ',     pos: 'DF' },
  { id: 1604, teamId: 16, num: 5,  name: 'トーマス デン', furi: 'とーます でん',  pos: 'DF' },
  { id: 1605, teamId: 16, num: 6,  name: '高木 善朗',  furi: 'たかぎ よしあき',   pos: 'MF' },
  { id: 1606, teamId: 16, num: 8,  name: '秋山 裕紀',  furi: 'あきやま ひろき',   pos: 'MF' },
  { id: 1607, teamId: 16, num: 10, name: '伊藤 涼太郎', furi: 'いとう りょうたろう', pos: 'MF' },
  { id: 1608, teamId: 16, num: 14, name: '島田 譲',    furi: 'しまだ ゆずる',     pos: 'MF' },
  { id: 1609, teamId: 16, num: 9,  name: 'アレクサンドル ゲデス', furi: 'あれくさんどる げです', pos: 'FW' },
  { id: 1610, teamId: 16, num: 11, name: '太田 修介',  furi: 'おおた しゅうすけ', pos: 'FW' },

  // 17: 東京ヴェルディ
  { id: 1701, teamId: 17, num: 1,  name: 'マテウス',   furi: 'まてうす',         pos: 'GK' },
  { id: 1702, teamId: 17, num: 3,  name: '宮原 和也',  furi: 'みやはら かずや',   pos: 'DF' },
  { id: 1703, teamId: 17, num: 4,  name: '林 尚輝',    furi: 'はやし なおき',     pos: 'DF' },
  { id: 1704, teamId: 17, num: 5,  name: '谷口 栄斗',  furi: 'たにぐち えいと',   pos: 'DF' },
  { id: 1705, teamId: 17, num: 6,  name: '綱島 悠斗',  furi: 'つなしま ゆうと',   pos: 'MF' },
  { id: 1706, teamId: 17, num: 8,  name: '森田 晃樹',  furi: 'もりた こうき',     pos: 'MF' },
  { id: 1707, teamId: 17, num: 10, name: '見木 友哉',  furi: 'みき ともや',       pos: 'MF' },
  { id: 1708, teamId: 17, num: 14, name: '齋藤 功佑',  furi: 'さいとう こうすけ', pos: 'MF' },
  { id: 1709, teamId: 17, num: 9,  name: '染野 唯月',  furi: 'そめの ゆづき',     pos: 'FW' },
  { id: 1710, teamId: 17, num: 11, name: '山田 楓喜',  furi: 'やまだ ふうき',     pos: 'FW' },

  // 18: 京都サンガF.C.
  { id: 1801, teamId: 18, num: 1,  name: '上福元 直人', furi: 'かみふくもと なおと', pos: 'GK' },
  { id: 1802, teamId: 18, num: 3,  name: '麻田 将吾',  furi: 'あさだ しょうご',   pos: 'DF' },
  { id: 1803, teamId: 18, num: 4,  name: '井上 黎生人', furi: 'いのうえ れいと',  pos: 'DF' },
  { id: 1804, teamId: 18, num: 5,  name: 'アピアタウ クベカ', furi: 'あぴあたう くべか', pos: 'DF' },
  { id: 1805, teamId: 18, num: 6,  name: '川崎 颯太',  furi: 'かわさき そうた',   pos: 'MF' },
  { id: 1806, teamId: 18, num: 8,  name: '福岡 慎平',  furi: 'ふくおか しんぺい', pos: 'MF' },
  { id: 1807, teamId: 18, num: 10, name: '武田 将平',  furi: 'たけだ しょうへい', pos: 'MF' },
  { id: 1808, teamId: 18, num: 14, name: '金子 大毅',  furi: 'かねこ だいき',     pos: 'MF' },
  { id: 1809, teamId: 18, num: 9,  name: 'ファジル マウコ', furi: 'ふぁじる まうこ', pos: 'FW' },
  { id: 1810, teamId: 18, num: 11, name: '豊川 雄太',  furi: 'とよかわ ゆうた',   pos: 'FW' },
]
